### ISSUE TITLE
What is the "Logseq will assign a new id for this block" error?

### ISSUE THREAD

**Issue by kerim** [logseq/graph-validator#5]
This is partially just curiosity, but also because no matter how often I re-index or do anything else the same errors show up every time (and it takes the validator script a long time to generate these errors as well). So what exactly does the "Logseq will assign a new id for this block" error mean, and is there some way to turn off this test?

**Comment by kerim** [comment]
So deleting the .recycle folder also solved this problem (except for one exception, which was a bak file).

**Comment by logseq-cldwalker** [comment]
This error message prints when two files have blocks with the same ids. It makes sense that removing bak and recycle files fixed the issue as those files can contain duplicated parts of files
