### ISSUE TITLE
Does failure matter for these two tests?

### ISSUE THREAD

**Issue by kerim** [logseq/graph-validator#7]
Thanks to your help and this CLI script, I've been able to clean up a lot of errors in my graph, however, the length of errors for the following two tests makes it seem impossible to fix manually. Is this something I should be concerned about? The two troublesome tests are:

assets-exist-and-are-used 
tags-and-page-refs-have-pages

Will it matter at all for graph performance if I leave these as-is without addressing the issues? Or perhaps there are scripts that could help clean these up automatically?

**Comment by logseq-cldwalker** [comment]
Glad to hear it's helped clear up errors.

> Is this something I should be concerned about?

I don't think you need to be concerned. It depends on if you value those particular validations. For `assets-exist-and-are-used`, it means your graph has links to nonexistent assets and/or that you have unused assets in your assets folder that are unused.  For `tags-and-page-refs-have-pages`, it means that you have tags and page-refs that aren't defined. This validation is useful for public and/or personal wikipedia graphs where you want every one of those concepts defined

> Will it matter at all for graph performance

Performance difference for this is negligible
