### ISSUE TITLE
PDF Highlights lead to validation errors

### ISSUE THREAD

**Issue by Dan-M** [logseq/graph-validator#8]
I am getting the following validation error after highlighting PDF's:

```
 Parsing graph ..
Parsing 361 files...
Ast node count: 9500

Testing logseq.graph-validator.default-validations
Found 23 block refs
Found 0 embed block refs
Found 10 queries
Found 48 assets

FAIL in (assets-exist-and-are-used) (:125)
All assets should be used
expected: (empty? (set/difference all-assets used-assets))
  actual: (not (empty? #{"vim-cheatsheet_1658990806295_0.edn"}))
```

Would it be possible to exclude assets that are created from highlighting from triggering this validation error?

Also I think it could be useful to have 2 separate tests:  `used-asset-exists` and `asset-is-used`.

**Comment by logseq-cldwalker** [comment]
Hi. Thanks for the report as pdf highlights shouldn't cause asset validations to fail. I hope to take a look by the end of the week

**Comment by logseq-cldwalker** [comment]
Sorry for the delay. This has been fixed. You can try the fix by setting the action to `logseq/graph-validator@main`

**Comment by Dan-M** [comment]
Works. Thank you.
